# Generated by Django 4.0.4 on 2022-08-10 12:02

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_referrals_options_referrals_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
