# Generated by Django 4.0.4 on 2022-06-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deposit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='added_to_balance',
            field=models.BooleanField(default=False),
        ),
    ]
