# Generated by Django 4.0.4 on 2022-08-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_country_alter_withdrawal_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='nationality',
        ),
    ]
