# Generated by Django 4.0.4 on 2022-06-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_deposit_added_to_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='added_to_balance',
        ),
    ]
