# Generated by Django 4.0.4 on 2022-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_country_profile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_amount',
            field=models.IntegerField(null=True),
        ),
    ]
