# Generated by Django 4.0.4 on 2022-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_deposit_trnx_hash_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
