# Generated by Django 4.0.4 on 2022-06-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_plans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
