# Generated by Django 4.0.4 on 2022-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_plans_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='intrest',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
