# Generated by Django 4.0.4 on 2022-06-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='duration',
        ),
    ]
