# Generated by Django 4.0.4 on 2022-06-30 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_investment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
