# Generated by Django 4.0.4 on 2022-07-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_investment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='date',
            new_name='created_at',
        ),
    ]
