# Generated by Django 4.0.4 on 2022-07-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_date_investment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='created_at',
            new_name='date',
        ),
    ]
