# Generated by Django 4.0.4 on 2022-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_created_at_investment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
