# Generated by Django 4.0.4 on 2022-07-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_investment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='expected',
            field=models.DateTimeField(default=None),
        ),
    ]
