# Generated by Django 4.0.4 on 2022-07-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_investment_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='expected',
            field=models.DateTimeField(),
        ),
    ]
