# Generated by Django 4.0.4 on 2022-07-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_investment_expected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='expected',
        ),
    ]
